///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: src/Music/primeraCancion.aks
/// Generation time: lu.,  3 de ene. de 2022 17:03:21
///

/// Song 'music' metadata macros
#define Newexplo_address  0x0040
#define Newexplo_size     0xC1
#define Newexplo_end      0x100

/// Song 'music' array declaration
extern void Newexplo[Newexplo_size];
